POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVra2FpIiwiaWQiOiI2NTFiMzJlODBmM2FjOTdkNjM0ODViOGQiLCJpYXQiOjE2OTYyODMxOTUsImV4cCI6MTY5NjI4Njc5NX0.GjJ1KNfxH5TmEh7c5I5Ck1_NQi3dLVEGY8ItBtiRvMg

{
"title": "Things I don't know as of 2018",
"author": "Dan Abramov",
"url": "https://overreacted.io/things-i-dont-know-as-of-2018/",
"likes": 0
}
